version: "2"  
services:  
  mysql:
     image: mysql:5.7
     container_name: mysql-name  # 容器的名称
     volumes:
       - ./dbdata:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 123456  # 数据库的密码
     ports:  
      - "3306:3306"  
     command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0