version: '3'
services:
  nexus:
    image: sonatype/nexus3:3.16.2
    container_name: nexus
    restart: always
    ports:
      - 8081:8081
    volumes:
      - ./nexus-data:/nexus-data
      - /etc/hosts:/etc/hosts
      # - /etc/localtime:/etc/localtime
# networks:
#   default:
#     external:
#       name: sec_net