version: '3'
services:
  registry:
    container_name: registry
    image: registry
    volumes:
    - ./data:/var/lib/registry
    - ./config.yml:/etc/docker/registry/config.yml
    expose:
      - 5000
    ports:
      - 5000:5000
    restart: always