version: '3'
services:
  jenkins:
    image: jenkins:2.60.3
    container_name: jenkins
    restart: always
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/hosts:/etc/hosts
      # - /etc/localtime:/etc/localtime